### ISSUE TITLE
github api-link code question

### ISSUE THREAD

**Issue by functor-soup** [devth/yetibot#585]
for the line in this [link](https://github.com/devth/yetibot/blob/master/src/yetibot/api/github.clj#L31)
`(alter-var-root #'tentacles.core/url (constantly endpoint))`

just was wondering if it is kosher to alter the variable as such given that a macro exists to change the url ?
could the macro mentioned in [this pr](https://github.com/Raynes/tentacles/pull/11) in the `tentacles` library not be used?

```
(defmacro with-url [new-url & body]
 `(binding [url ~new-url]
    ~@body))
```

**Comment by devth** [comment]
Yes, you're right. I must have missed that macro when I originally wrote this. It should be switched to use `with-url`.

**Comment by devth** [comment]
@functor-soup would you like to fix this or shall I?

**Comment by functor-soup** [comment]
@devth sorry man, did not even see this till now. I see it's not in master and neither in any of the branches. Will take a crack at this hopefully this week.

**Comment by devth** [comment]
Thanks & no worries!

**Comment by functor-soup** [comment]
@devth haven't forgotten about this, will do it over this weekend

**Comment by devth** [comment]
@functor-soup awesome, thanks!

By the way, I've started organizing tasks to work on at [this Waffle board](https://waffle.io/devth/yetibot/join), including some really fun tasks and some super easy ones. Feel free to tackle any in the "Ready" column.

Also: I hope the 0.4 upgrade / config migration wasn't too painful for you. Let me know if it was and if I need to improve the docs.

**Comment by functor-soup** [comment]
@devth, the upgrade/ migration was fine though the core could have been descriptive with it's error msg. Will open on a ticket on core on further investigation

this ticket is in progress? could you make a collaborator so I can move the card on the waffle board?

**Comment by devth** [comment]
@functor-soup made you a collaborator!

**Comment by functor-soup** [comment]
@devth a pr is in queue, but I seem to be failing this thing with diff percentages, just wondering why the threshold is so high?

**Comment by devth** [comment]
@functor-soup no idea :) I'm just trying out the codecov stuff. Don't have time to look at it this second. I'll see if I can adjust things, or if not I'll merge anyway.
