### ISSUE TITLE
Run yetibot behind a proxy

### ISSUE THREAD

**Issue by rhoml** [devth/yetibot#664]
Is there support to run yetibot behind an http proxy? I'd like also to be able to choose domains / ips to not route through the proxy

**Comment by devth** [comment]
It's not explicitly supported by Yetibot itself, but it is supported on the JVM. Yetibot uses clj-http for its http client, which has a [Proxies](https://github.com/dakrone/clj-http#proxies) section that documents how to set it up.

Does that work?

**Comment by devth** [comment]
@rhoml closing this issue. Feel free to re-open if the above doesn't work for you.
